"use server";

import { HotelCardProps } from "@/lib/types/hotel-card";
import prisma from "@/lib/prisma";
import { get10HotelsOf5Provinces } from "../generated/prisma/sql";


type FeedProps = { provinceName: string, hotels: HotelCardProps[] }[];

// TODO: fix any. This is generated by AI and it uses a lot of 'any's.
export async function fetchFeed(): Promise<FeedProps> {
  const rows = await prisma
    .$queryRawTyped(get10HotelsOf5Provinces());

  return rows
    .filter((item: any) => item.hotels != null)
    .map((item: any) => ({
      provinceName: item.province_name,
      hotels: (item.hotels as any[]).map((h: any) => {
        // normalize fields and types
        const imageUrls = Array.isArray(h.imageUrls) ? h.imageUrls : (h.imageUrls ? JSON.parse(h.imageUrls) : []);
        const facilities = Array.isArray(h.facilities) ? h.facilities : (h.facilities ? JSON.parse(h.facilities) : []);
        const minPrice = h.minPrice ?? h.min_price ?? null;

        return {
          id: h.id,
          name: h.name,
          imageUrls,
          reviewPoints: typeof h.reviewPoints === 'string' ? Number(h.reviewPoints) : h.reviewPoints,
          numberOfReviews: typeof h.numberOfReviews === 'string' ? Number(h.numberOfReviews) : h.numberOfReviews,
          // build nested ward -> district -> province shape expected by HotelCardProps
          ward: {
            name: h.wardName ?? h.ward_name ?? null,
            district: { province: { name: item.province_name } },
          },
          facilities: facilities.map((f: any) => ({ name: f.name })),
          // roomTypes expected as array; use minPrice as single entry if available
          roomTypes: minPrice == null ? [] : [{ price: Number(minPrice) }],
          type: h.type,
        };
      }) as HotelCardProps[],
    }));
}